add_newline = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration
$character
"""

[username]
show_always = true
style_user = "bold cyan"

[hostname]
ssh_only = false
style = "bold blue"

[directory]
style = "bold yellow"
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold green"

[git_status]
style = "bold red"

[cmd_duration]
min_time = 100
style = "bold magenta"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
