# =============================================================================
# Starship Prompt Configuration
#
# Projekt : Terminal Environment
# Version : 0.1.0
#
# Beschreibung:
# Grundkonfiguration des Starship-Prompts.
# Zusätzliche Module werden schrittweise ergänzt.
# =============================================================================

add_newline = true


format = """
[$username$hostname](bold green)$directory$git_branch$git_status$character$fill$battery$time(bg:#1C3A5E fg:#8DFBD2)
[└─>](bold green) """

#$username\
#$hostname\

#$directory\
#$git_branch\
#$git_status
#$character
#"""


[username]
show_always = true
style_user = "bold blue"
style_root = "bold red"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold cyan"
format = "@[$hostname]($style)"

[directory]
style = "bold yellow"
truncate_to_repo = false
truncation_length = 0

[git_branch]
symbol = "\ue0a0 "
style = "bold green"
format = "[$symbol$branch]($style)"
truncation_length = 32

[git_status]
style = "bold yellow"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = "✓"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
format = '([\[$all_status$ahead_behind\]]($style))'

[cmd_duration]
min_time = 100
style = "bold magenta"

[character]
success_symbol = "[❯](bold cyan)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'


[battery]
full_symbol = "󰁹"
charging_symbol = "󰂄"
discharging_symbol = "󰁺"
format = "[$symbol $percentage]($style)"